---
name: action-name
on: push
jobs:
  test:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Sleep 3m
        run: |
          sleep 180
